Newscoop\Entity\Publication:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            read_only: true
            groups: ["list", "details"]
            serialized_name: id
        name:
            expose: true
            read_only: true
            groups: ["list", "details"]
            serialized_name: name