Newscoop\Entity\Snippet:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            read_only: true
            type: integer
            groups: ["details", "list"]
            serialized_name: id
        name:
            expose: true
            read_only: true
            type: string
            groups: ["details", "list"]
            serialized_name: name
        fields:
            expose: true
            read_only: true
            type: array
            groups: ["details", "list"]
            serialized_name: fields
            accessor:
                getter: getFields
        template:
            expose: true
            read_only: true
            type: string
            groups: ["details", "list"]
            serialized_name: template
            accessor:
                getter: getTemplateName
    virtual_properties:
        getTemplateId:
            expose: true
            read_only: true
            type: integer
            groups: ["details", "list"]
            serialized_name: templateId
            accessor:
                getter: getTemplateId
        # commenter:
        #     expose: true
        #     read_only: true
        #     groups: ["details", "list"]
        #     type: string
        #     accessor:
        #         getter: getCommenterName
        #         setter: setCommenterName
        #     serialized_name: author
        # parent:
        #     expose: true
        #     read_only: true
        #     type: integer
        #     accessor:
        #         getter: getParentId
        #     groups: ["details", "list"]
        #     serialized_name: parent
        #     since_version: 1.1
        # thread_level:
        #     expose: true
        #     read_only: true
        #     type: integer
        #     groups: ["details", "list"]
        #     serialized_name: thread_level
        #     since_version: 1.1
        # thread_order:
        #     expose: true
        #     read_only: true
        #     type: integer
        #     groups: ["details", "list"]
        #     serialized_name: thread_order
        #     since_version: 1.1
        # recommended:
        #     expose: true
        #     read_only: true
        #     type: integer
        #     groups: ["details", "list"]
        #     serialized_name: recommended
        #     since_version: 1.1
        # status:
        #     expose: true
        #     read_only: true
        #     type: string
        #     groups: ["details", "list"]
        #     serialized_name: status
        #     access_type: public_method
        #     since_version: 1.1